export const
CHANGE_FIRST_NAME_TEXT = 'CHANGE_FIRST_NAME_TEXT',
CHANGE_LAST_NAME_TEXT = 'CHANGE_LAST_NAME_TEXT',
CHANGE_EMAIL_TEXT = 'CHANGE_EMAIL_TEXT',
CHANGE_PASSWORD_TEXT = 'CHANGE_PASSWORD_TEXT',
SHOW_PASSWORD = 'SHOW_PASSWORD',
HIDE_PASSWORD = 'HIDE_PASSWORD'